version: 2.1

jobs:
  build-and-test:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Install CMake
          command: |
            apt-get update
            apt-get install -y cmake
      - run:
          name: Create Build Directory
          command: |
            rm -rf build
            mkdir build
      - run:
          name: Run CMake
          command: |
            cd build
            cmake ..
      - run:
          name: Build Project
          command: |
            cd build
            cmake --build . --verbose
      - run:
          name: Run Tests
          command: ./build/MyTests  

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test