version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/cpp:latest  # Or choose an appropriate C++ image
    steps:
      - checkout
      - run: mkdir build
      - run: cd build && cmake ..
      - run: cmake --build .
      - run: ./MyTests  # Run your tests

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test