version: 2.1

jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake ..
            make

  test:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./build/MyTests  