version: 2.1

jobs:
  build-and-test:
    docker:
      - image: conanio/gcc11  # Use a Conan Docker image with gcc
    steps:
      - checkout

      - run:
          name: Setup Conan and CMake
          command: |
            pip install conan
            conan --version  # Verify Conan installation
            conan profile new default --detect  # Create a default profile
            conan profile update settings.compiler.libcxx=libstdc++11 default
            apt-get update
            apt-get install -y cmake clang clang-tools clang-tidy clang-format

      - run:
          name: Install Dependencies with Conan
          command: |
            mkdir -p build
            cd build
            conan install .. --build=missing -s build_type=Release

      - run:
          name: Configure Project with CMake
          command: |
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release

      - run:
          name: Build Project
          command: |
            cd build
            cmake --build .

      - run:
          name: Run Tests
          command: |
            ./build/MyTests

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
