version: 2.1

jobs:
  build-and-test:
    docker:
      - image: gcc:latest  # Using GCC Docker image
    steps:
      - checkout
      - run:
          name: Create Build Directory
          command: mkdir build
      - run:
          name: Run CMake
          command: |
            cd build
            cmake ..
      - run:
          name: Build Project
          command: cmake --build .
      - run:
          name: Run Tests
          command: ./build/MyTests  # Adjust the path to your test executable

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test