version: 2.1

jobs:
  build-and-test:
    docker:
      - image: gcc:latest  # Consider using an image with Python pre-installed
    steps:
      - checkout

      - run:
          name: Install Python, Pip, and Conan
          command: |
            apt-get update
            apt-get install -y python3 python3-pip
            pip3 install conan
            conan --version  # Verify Conan installation

      - run:
          name: Install CMake, Clang, and Clang Tools
          command: |
            apt-get install -y cmake clang clang-tools clang-tidy
            apt-get install -y clang-format-16
            update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-16 100

      - run:
          name: Verify ClangFormat Version
          command: |
            clang-format --version

      - run:
          name: Install Dependencies with Conan
          command: |
            mkdir -p build
            cd build
            conan install .. --build=missing

      - run:
          name: Configure Project with CMake
          command: |
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake

      - run:
          name: Build Project
          command: |
            cd build
            cmake --build . --verbose

      - run:
          name: Run Tests
          command: |
            ./build/MyTests

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
